os:
  - linux
  - osx
  
# due to we are sure about the MacOSX version, I tollerate build failures under osx
matrix:
  allow_failures:
    - os: osx
  
sudo: false

language: perl

# normally cpanm is called for perl, but we do not need it so skip the installation of dependencies
install: true

script:
  - cd t
  - ./test.sh
